trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  displayName: Install Latest .NET Core 3.1 SDK
  inputs:
    packageType: 'sdk'
    version: '3.1.x'

- task: DotNetCoreCLI@2
  displayName: Publish CLI
  inputs:
    command: 'publish'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/CLI'
    workingDirectory: '$(System.DefaultWorkingDirectory)/NumberCombinationGeneratorCli'

- task: DotNetCoreCLI@2
  displayName: Publish Blazor App
  inputs:
    command: 'publish'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/WebApp'
    workingDirectory: '$(System.DefaultWorkingDirectory)/NumberCombinationGenerator'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts'
  inputs:
    pathtoPublish: $(Build.ArtifactStagingDirectory)
    artifactName: 'drop'